before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libmysqlclient-dev libmysqlclient18 libgtop2-7 libgtop2-common libgtop2-dev
- ./autogen.sh
install: make get-deps
language: c
compiler: gcc