before_script:
- sudo add-apt-repository ppa:dns/gnu -y
- sudo apt-get update -qq
- sudo apt-get install -qq libmysqlclient-dev libmysqlclient18 libgtop2-7 libgtop2-common libgtop2-dev mysql-server mysql-client
- sudo apt-get install --only-upgrade autoconf
- sudo mysql -e 'CREATE DATABASE spine'
- sudo mysql -D spine < ./sql/spine-db.sql
- sudo mysql -e 'show databases'
script: cd spine-agent && ./autogen.sh && ./configure && make && make check
language: c
compiler: gcc