before_install:
- sudo add-apt-repository ppa:dns/gnu -y
- sudo apt-get update -qq
- sudo apt-get install -qq libmysqlclient-dev libmysqlclient18 libgtop2-7 libgtop2-common libgtop2-dev
- sudo apt-get install --only-upgrade autoconf
script: cd spine-agent && ./autogen.sh && ./configure && make && make check
language: c
compiler: gcc